project:
  type: website

website:
  title: "Jasmijn Bazen"
  navbar:
    left:
      - href: index.qmd
        text: About me
      - href: MyExperience.qmd
        text: My Experience

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



