---
title: "My Experience"
---

Below you can find an overview of my experience and interests. 

# Methods and Statistics

## Research Master
I am currently completing a research master's degree at the University of Utrecht in _Methodology and Statistics for the Behavioural, Biomedical and Social Sciences_ (MSBBSS) or simply Methods and Statistics.\\
This programme has provided me with an in-depth understanding of widely used statistical methods, including multilevel modelling, Bayesian statistics, structural equation modelling, analysing survey data, and more. You can find the official programme page [here](https://www.uu.nl/en/masters/methodology-and-statistics-behavioural-biomedical-and-social-sciences)\\
For my electives, I chose courses at Cito, where I studied: _Contemporary Datasets_, _Psychometrics and Data Science_, and _Bayesian Psychometrics_. These courses allowed me to further specialise in (Bayesian) psychometrics, the use of machine learning, and working with realistic datasets resembling real-life scenarios.
### Master's Thesis 
For my Masters' thesis, I am evaluating the impact of test motivation on PISA and TIMSS Outcomes, where test motivation is measured by missing answers to questions and response times. PISA and TIMSS are both Internal Large-Scale Assessment studies (ILSAs).

## Bachelor
I have previously completed my Bachelors in Psychology at the University of Twente. Alongside the standard programme, I followed the elective modules Psychology of Safety, and Human factors & Engineering Psychology, as well as completed a minor abroad in Madrid. \\
- The _Bachelor Psychology_ provided me with the basic psychology facts and thought processes helpful in both everyday life as well as for academic purposes.\\
- The module _Psychology of Safety_ taught me how to influence individual responses to risks and safety issues, such as proper crowd control when disasters occur. \\
- _Human factors & Engineering Psychology_ offered great insight into how one can implement psychological findings into designing websites, daily user objects, apps, or even cars.  As a part of this module, I completed a project programming an eye-tracking device using Python, a ruler, and a cheap camera. \\ 
- The minor was focused on companies, their structures and their management.
### Thesis 
My Bachelor thesis focused on the statistical analysis of electroencephalogram (EEG) trial data through _Bayesian covariance structure modelling (BCSM)_. I conducted a simulation study for the evaluation of the BCSM compared to a linear mixed effects model for different sample sizes and covariance values. The BCSM was then applied to electroencephalogram (EEG) trial data. 

# Work Experience
I have individually taught several practicals at the University of Utrecht in the subject Kennismaking met onderzoeksmethoden en statistiek, or KOM for short. This course aims to introduce first year students to qualitative, correlational and experimental research. You can find the Osiris page [here](https://www.uu.nl/swcursus/201800051)\\
I have worked as a student assistant in the summer school course Statistical Programming with R. Teaching students R from the basics, from data visualisation till bootstrapping.  

# Student activism 
Over the years, I have been a member of committees of my sports associations in Enschede for a total of 6 years. Next to this, I have occupied the position of Internal Affairs for my main association for a year now, with half a year left to go. For now, you can find me and my other board members [here](https://www.stretchers.nl/info/bestuur)

# My Skillset
- Proficient in R
- Basic understanding of Python
- Strong grasp of fundamental statistical methods, with the ability to quickly learn and apply new techniques
- Psychological background, enabling me to provide meaningful context to analyses
